--===================================================
-- File Name    : player.lua
-- Creator      : yestein (yestein86@gmail.com)
-- Date         : 2013-08-07 13:08:52
-- Description  :
-- Modify       :
--===================================================
